version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: next-app
    tty: true
    restart: always
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
    # working_dir: '/app'
    expose:
      - '4000'
    networks:
      services-vax-platform:
        ipv4_address: 10.10.0.22

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./backend/docker/nginx_conf:/etc/nginx/conf.d
      - ./backend/:/var/www/html
    depends_on:
      - php
    networks:
      services-vax-platform:
        ipv4_address: 10.10.0.72

  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    container_name: vax-api
    restart: always
    tty: true
    ports:
      - '5173:5173'
    volumes:
      - ./backend/:/var/www/html
      - /usr/bin/ssh:/usr/bin/ssh
    working_dir: '/var/www/html'
    environment:
      - PHP_IDE_CONFIG=serverName=Local
    networks:
      services-vax-platform:
        ipv4_address: 10.10.0.82

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=vaccines_api_db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./backend/data/volumes/postgres:/var/lib/postgresql/data
      - ./backend/data/dump:/var/lib/postgresql/dump
    networks:
      services-vax-platform:
        ipv4_address: 10.10.0.32

networks:
  services-vax-platform:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/20
